# Generated by Django 3.0.6 on 2020-05-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('plant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Inverter'), (2, 'Scb'), (3, 'Em'), (4, 'Ws'), (5, 'Mfm')])),
                ('block_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('status', models.CharField(default='INIT', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
            ],
        ),
    ]
