# Generated by Django 3.0.6 on 2020-06-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20200602_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndPoints',
            new_name='EndPoint',
        ),
        migrations.RenameModel(
            old_name='TargetUris',
            new_name='TargetUri',
        ),
    ]
